name: Generate Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/generate-documentation.yml@main
    inputs:
      entry-point: src/main.ts
