name: Generate Documentation

on:
  release:
    types: [published]

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/generate-documentation.yml@main
    inputs:
      entry-point: src/main.ts
